version: 0.1

phases:
  install:
    commands:
      - printenv
      - rm -rf node_modules
      - npm install
  build:
    commands:
      - npm run build -prod
  post_build:
    commands:
      - aws --region EU-WEST-1 s3 sync ./dist/ s3://makerlabcodebucket-ekimr/ --acl=public-read --delete
